### ISSUE TITLE
if illegal character in driver name it raises an error while importing

### ISSUE THREAD

**Issue by studioj** [Shivanshu26shiv/devcon_win#2]
```
import devcon_win_copy
  File "c:\python27\lib\site-packages\devcon_win\devcon_win_copy.py", line 590
    def TSSTcorp_DVD+_RW_SH_216DB(arg='status'):
                    ^
SyntaxError: invalid syntax
```

if there is a + in the driver name => which is allowed it will not be able to import

If you want i can have a look to not generate the separate file anymore. I can also give you some help with packaging the whole thing in a proper python package together with the executable. Let me know if you're interested and I'll fork up some changes.

Kr

**Comment by Shivanshu26shiv** [comment]
> ```
> import devcon_win_copy
>   File "c:\python27\lib\site-packages\devcon_win\devcon_win_copy.py", line 590
>     def TSSTcorp_DVD+_RW_SH_216DB(arg='status'):
>                     ^
> SyntaxError: invalid syntax
> ```
> 
> if there is a + in the driver name => which is allowed it will not be able to import
> 
> If you want i can have a look to not generate the separate file anymore. I can also give you some help with packaging the whole thing in a proper python package together with the executable. Let me know if you're interested and I'll fork up some changes.
> 
> Kr

Hey @studioj, thank you for the analysis and details. 
Yes, I would love to avoid creating a separate file, if the new approach allows me the same display of all the drivers on "Ctrl+space". 

For other issues of special character and exe packaging, please feel free to fork up desired changes.

**Comment by studioj** [comment]
> > ```
> > import devcon_win_copy
> >   File "c:\python27\lib\site-packages\devcon_win\devcon_win_copy.py", line 590
> >     def TSSTcorp_DVD+_RW_SH_216DB(arg='status'):
> >                     ^
> > SyntaxError: invalid syntax
> > ```
> > 
> > 
> > if there is a + in the driver name => which is allowed it will not be able to import
> > If you want i can have a look to not generate the separate file anymore. I can also give you some help with packaging the whole thing in a proper python package together with the executable. Let me know if you're interested and I'll fork up some changes.
> > Kr
> 
> Hey @studioj, thank you for the analysis and details.
> Yes, I would love to avoid creating a separate file, if the new approach allows me the same display of all the drivers on "Ctrl+space".
> 
> For other issues of special character and exe packaging, please feel free to fork up desired changes.

If you really want your specific driver to autocomplete in basic editors like VSCode then there is no other way than generating a second file.

I can give it a go, if you believe its integratable we can merge my code in the repo.

I also want to implement a CI/CD system with travis which could be able to auto release

**Comment by Shivanshu26shiv** [comment]
`If you really want your specific driver to autocomplete in basic editors like VSCode then there is no other way than generating a second`
True that, then second file is necessary.

`
I can give it a go, if you believe its integratable we can merge my code in the repo
`
Please be my guest.

`I also want to implement a CI/CD system with travis which could be able to auto release`
Sounds cool but this was just a small project, I would suggest to go for it only if you have spare time :)

Meanwhile you can add illegal character support and update the code if you want. Let me know if you want me to add you as a contributor.

**Comment by Shivanshu26shiv** [comment]
Thanks! Merged the code, closing the issue.
